builds:
- env:
  - CGO_ENABLED=0
  goos:
    - windows
    - darwin
    - linux
  goarch:
    - amd64
    - 386
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
archive:
  format: binary
  replacements:
    386: i386
    amd64: x86_64
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
