language: go
go:
  - 1.12.x
env:
  - GO111MODULE=on
cache:
  directories:
     - $HOME/gopath/pkg/mod
install:
  - go mod download
script:
  - go test -v ./...
after_success: |
  if [ ! -z "$TRAVIS_TAG" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
    curl -sL https://github.com/goreleaser/goreleaser/releases/download/v0.97.0/goreleaser_Linux_x86_64.tar.gz | tar zx -C ~ goreleaser
    ~/goreleaser
  fi
notifications:
  email:
    on_success: never
    on_failure: never
