[package]
name = "haken"
version = "0.1.0"
authors = ["rot1024 <aayhrot@gmail.com>"]
description = "anime selector"

[dependencies]
clap = {version = "2.29.0", features = ["yaml"]}
console = "0.5.0"
hyper = "0.11.9"
hyper-tls = "0.1.2"
select = "0.4.2"
tokio-core = "0.1.11"
futures = "0.1.17"
